project:
  type: book
  
book:
  title: "Embedding Analysis and Numerical Reasoning in Language Models"
  author: "Emanuele Gentiletti"
  date: "2024-2025"
  chapters:
    - index.qmd
    - src/01-intro.qmd
    - src/02-implementation.qmd
    - src/99-bibliography.qmd
  downloads: [pdf]
  
bibliography: src/bibliography.bib
csl: apa.csl

format:
  html:
    theme: cosmo
    code-fold: true
    code-tools: true
    toc: true
    number-sections: true
    
  pdf:
    documentclass: book
    classoption: [a4paper, twoside, 10pt, titlepage]
    geometry: 
      - left=3.5cm
      - right=3cm
      - top=2.5cm
      - bottom=3cm
    mainfont: Palatino
    monofont: hacknerdfontmonoregular
    titlepage: false
    pdf-engine: lualatex
    toc: true
    number-sections: true
    colorlinks: true
    cite-method: citeproc
    keep-tex: true
    include-in-header: src/header.tex
    include-before-body: src/frontmatter.tex

lang: en
link-citations: true
code-block-captions: true
